export const GET_REPO_INFO = "GET_REPO_INFO"
export const GET_REPO_INFO_SUCCESS = "GET_REPO_INFO_SUCCESS"

export const FETCH_REPO_SUCCESS = "FETCH_SUCCESS"
export const FETCH_REPO_ERROR = "FETCH_ERROR"

export const FETCH_MORE_REPO = "FETCH_MORE_REPO"
export const FETCH_MORE_REPO_SUCCESS = "FETCH_MORE_REPO_SUCCESS"