export const FETCH_STARGAZER = "FETCH_STARGAZER"
export const FETCH_STARGAZER_SUCCESS = "FETCH_STARGAZER_SUCCESS"

export const FETCH_MORE_STARGAZER = "FETCH_MORE_STARGAZER"
export const FETCH_MORE_STARGAZER_SUCCESS = "FETCH_MORE_STARGAZER_SUCCESS"

export const FETCH_STARGAZER_ERROR = "FETCH_STARGAZER_ERROR"
